# Generated by Django 4.1 on 2022-09-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesion',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
